---
title: "Homework 6"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(MASS)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_bw() + theme(legend.position = "bottom"))
```

# Problem 1: tidying
```{r}
## load in dataset

birth_data = 
  read_csv(file = "./data/birthweight.csv")

## clean dataset and convert categorical variables to factors
birth_data %>%
  janitor::clean_names() %>%
  mutate(babysex = as.factor(babysex),
         frace = as.factor(frace),
         malform = as.factor(malform),
         mrace = as.factor(mrace))

## check for missing data

birth_data %>%
  map_df(~sum(is.na(.)))

```
I loaded the dataset, cleaned it as appropriate data types, and checked for missing values. There are none so I can proceed with analyses.

## linear models

I am using a stepwise model building process to test what variables are associated with birth weight in my dataset. 

```{r}
# pulling all of my variables into one equation
model_1 = lm(bwt ~ ., data = birth_data)

# doing a stepwise model selection based on AIC
model1_step = stepAIC(model_1, direction = "both")

# summarizing the above model
summary(model1_step)

# plotting the residuals
plot(model1_step, scale = "r2")

```

